### ISSUE TITLE
Info.plist is missing

### ISSUE THREAD

**Issue by MartinW** [rwapp/A11y-Box-iOS#21]
Info.plist is missing for the project and the unit tests. 

This prevents the project from building.

**Comment by rwapp** [comment]
Thanks Martin. Seems git think's I've added them to .gitignore, but I can't see a matching rule. I'll push a new commit shortly.

**Comment by rwapp** [comment]
Should be fixed. Please verify when you can.

**Comment by MartinW** [comment]
Verified as working
